import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "@/app/providers";
import ErrorBoundary from "@/app/error-boundary";
import { Toaster } from "sonner";

const geist = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

const fontMono = Noto_Sans_Mono({
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				fontMono.variable,
				"font-sans",
				geist.variable,
			)}
		>
			<body className="flex min-h-full flex-col">
				<Providers>
					<ErrorBoundary title="Card info form Error">
						<main>{children}</main>
					</ErrorBoundary>
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
